name: Build Android APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config \
            zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev android-tools-adb \
            build-essential libsdl2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33 pillow
          pip install -r requirements.txt
          pip install -r kahiin/requirements.txt

      - name: Update git submodules
        run: |
          git submodule update --remote --merge

      - name: Build with buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          export JAVA_HOME=/opt/hostedtoolcache/Java/11/x64
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kahiin-apk
          path: bin/*.apk
          retention-days: 90

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*.apk
          generate_release_notes: true