name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Update git submodules
        run: git submodule update --init --recursive

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt
          pip install -r kahiin/requirements.txt

      - name: Build with Buildozer action
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        id: buildozer
        with:
          buildozer_version: stable

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kahiin-apk
          path: ${{ steps.buildozer.outputs.filename }}
          retention-days: 90

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.buildozer.outputs.filename }}
          generate_release_notes: true